// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC31dHF_6s7hLii54BIV0pi18FlTdYxBco',
    appId: '1:362526751061:web:dc5894abc4032f9b18d7dc',
    messagingSenderId: '362526751061',
    projectId: 'projectmanagementfluttercli',
    authDomain: 'projectmanagementfluttercli.firebaseapp.com',
    storageBucket: 'projectmanagementfluttercli.firebasestorage.app',
    measurementId: 'G-T5LZ9JN3CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaqabV5j5bT6XGSKgOW1bVGwVwGHAfGSY',
    appId: '1:362526751061:android:aae0eb595f630b4718d7dc',
    messagingSenderId: '362526751061',
    projectId: 'projectmanagementfluttercli',
    storageBucket: 'projectmanagementfluttercli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB1NGJlxC67y75kGcfzJmMcxxBMHpQUrQ',
    appId: '1:362526751061:ios:0d65402051e6f36518d7dc',
    messagingSenderId: '362526751061',
    projectId: 'projectmanagementfluttercli',
    storageBucket: 'projectmanagementfluttercli.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirebaseStorageFlutterfireCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB1NGJlxC67y75kGcfzJmMcxxBMHpQUrQ',
    appId: '1:362526751061:ios:0d65402051e6f36518d7dc',
    messagingSenderId: '362526751061',
    projectId: 'projectmanagementfluttercli',
    storageBucket: 'projectmanagementfluttercli.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirebaseStorageFlutterfireCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC31dHF_6s7hLii54BIV0pi18FlTdYxBco',
    appId: '1:362526751061:web:4cfa5dd60f7a69f618d7dc',
    messagingSenderId: '362526751061',
    projectId: 'projectmanagementfluttercli',
    authDomain: 'projectmanagementfluttercli.firebaseapp.com',
    storageBucket: 'projectmanagementfluttercli.firebasestorage.app',
    measurementId: 'G-VY753S6BRD',
  );
}
